columns:
- input_type: number
  label: EmployeeId
  name: EmployeeId
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: text
  label: LastName
  name: LastName
  nullable: true
  primary_key: 0
  type: NVARCHAR(20)
- input_type: text
  label: FirstName
  name: FirstName
  nullable: true
  primary_key: 0
  type: NVARCHAR(20)
- input_type: text
  label: Title
  name: Title
  nullable: true
  primary_key: 0
  type: NVARCHAR(30)
- input_type: number
  label: ReportsTo
  name: ReportsTo
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: date
  label: BirthDate
  name: BirthDate
  nullable: true
  primary_key: 0
  type: DATETIME
- input_type: date
  label: HireDate
  name: HireDate
  nullable: true
  primary_key: 0
  type: DATETIME
- input_type: text
  label: Address
  name: Address
  nullable: true
  primary_key: 0
  type: NVARCHAR(70)
- input_type: text
  label: City
  name: City
  nullable: true
  primary_key: 0
  type: NVARCHAR(40)
- input_type: text
  label: State
  name: State
  nullable: true
  primary_key: 0
  type: NVARCHAR(40)
- input_type: text
  label: Country
  name: Country
  nullable: true
  primary_key: 0
  type: NVARCHAR(40)
- input_type: text
  label: PostalCode
  name: PostalCode
  nullable: true
  primary_key: 0
  type: NVARCHAR(10)
- input_type: text
  label: Phone
  name: Phone
  nullable: true
  primary_key: 0
  type: NVARCHAR(24)
- input_type: text
  label: Fax
  name: Fax
  nullable: true
  primary_key: 0
  type: NVARCHAR(24)
- input_type: text
  label: Email
  name: Email
  nullable: true
  primary_key: 0
  type: NVARCHAR(60)
name: EmpView
type: view
