columns:
- input_type: number
  label: InvoiceId
  name: InvoiceId
  nullable: false
  primary_key: 1
  type: INTEGER
- input_type: number
  label: CustomerId
  name: CustomerId
  nullable: false
  primary_key: 0
  type: INTEGER
- input_type: date
  label: InvoiceDate
  name: InvoiceDate
  nullable: false
  primary_key: 0
  type: DATETIME
- input_type: text
  label: BillingAddress
  name: BillingAddress
  nullable: true
  primary_key: 0
  type: NVARCHAR(70)
- input_type: text
  label: BillingCity
  name: BillingCity
  nullable: true
  primary_key: 0
  type: NVARCHAR(40)
- input_type: text
  label: BillingState
  name: BillingState
  nullable: true
  primary_key: 0
  type: NVARCHAR(40)
- input_type: text
  label: BillingCountry
  name: BillingCountry
  nullable: true
  primary_key: 0
  type: NVARCHAR(40)
- input_type: text
  label: BillingPostalCode
  name: BillingPostalCode
  nullable: true
  primary_key: 0
  type: NVARCHAR(10)
- input_type: text
  label: Total
  name: Total
  nullable: false
  primary_key: 0
  type: NUMERIC(10, 2)
name: Invoice
