columns:
- autoincrement: true
  input_type: number
  label: id
  name: id
  nullable: true
  primary_key: 1
  type: INTEGER
- input_type: text
  label: file_name
  name: file_name
  nullable: false
  primary_key: 0
  type: VARCHAR(255)
- input_type: text
  label: file_type
  name: file_type
  nullable: false
  primary_key: 0
  type: VARCHAR(50)
- input_type: number
  label: file_size
  name: file_size
  nullable: false
  primary_key: 0
  type: INTEGER
- input_type: text
  label: file_path
  name: file_path
  nullable: false
  primary_key: 0
  type: VARCHAR(255)
- input_type: number
  label: uploaded_by
  name: uploaded_by
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: text
  label: title
  name: title
  nullable: true
  primary_key: 0
  type: VARCHAR(255)
- input_type: text
  label: description
  name: description
  nullable: true
  primary_key: 0
  type: TEXT
- input_type: text
  label: alt_text
  name: alt_text
  nullable: true
  primary_key: 0
  type: VARCHAR(255)
- input_type: date
  label: created_at
  name: created_at
  nullable: false
  primary_key: 0
  type: DATETIME
- input_type: date
  label: updated_at
  name: updated_at
  nullable: false
  primary_key: 0
  type: DATETIME
name: media
type: table
