columns:
- autoincrement: true
  input_type: number
  label: id
  name: id
  nullable: true
  primary_key: 1
  type: INTEGER
- input_type: number
  label: post_id
  name: post_id
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: text
  label: meta_title
  name: meta_title
  nullable: true
  primary_key: 0
  type: VARCHAR(200)
- input_type: text
  label: meta_description
  name: meta_description
  nullable: true
  primary_key: 0
  type: TEXT
- input_type: text
  label: meta_keywords
  name: meta_keywords
  nullable: true
  primary_key: 0
  type: TEXT
- input_type: text
  label: og_title
  name: og_title
  nullable: true
  primary_key: 0
  type: VARCHAR(200)
- input_type: text
  label: og_description
  name: og_description
  nullable: true
  primary_key: 0
  type: TEXT
- input_type: text
  label: og_image
  name: og_image
  nullable: true
  primary_key: 0
  type: VARCHAR(255)
- input_type: date
  label: created_at
  name: created_at
  nullable: false
  primary_key: 0
  type: DATETIME
- input_type: date
  label: updated_at
  name: updated_at
  nullable: false
  primary_key: 0
  type: DATETIME
name: seo_metadata
type: table
