columns:
- autoincrement: true
  input_type: number
  label: id
  name: id
  nullable: true
  primary_key: 1
  type: INTEGER
- input_type: text
  label: name
  name: name
  nullable: false
  primary_key: 0
  type: VARCHAR(50)
- input_type: text
  label: slug
  name: slug
  nullable: false
  primary_key: 0
  type: VARCHAR(50)
- input_type: text
  label: description
  name: description
  nullable: true
  primary_key: 0
  type: TEXT
- input_type: date
  label: created_at
  name: created_at
  nullable: false
  primary_key: 0
  type: DATETIME
cols:
  id:
    autoincrement: true
    input_type: number
    label: id
    name: id
    nullable: true
    primary_key: 1
    type: INTEGER
  name:
    input_type: text
    label: name
    name: name
    nullable: false
    primary_key: 0
    type: VARCHAR(50)
  slug:
    input_type: text
    label: slug
    name: slug
    nullable: false
    primary_key: 0
    type: VARCHAR(50)
  description:
    input_type: text
    label: description
    name: description
    nullable: true
    primary_key: 0
    type: TEXT
  created_at:
    input_type: date
    label: created_at
    name: created_at
    nullable: false
    primary_key: 0
    type: DATETIME
name: tags
type: table
