columns:
- autoincrement: true
  input_type: number
  label: id
  name: id
  nullable: true
  primary_key: 1
  type: INTEGER
- input_type: number
  label: issue_id
  name: issue_id
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: number
  label: user_id
  name: user_id
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: number
  label: hours
  name: hours
  nullable: false
  primary_key: 0
  type: FLOAT
- input_type: text
  label: comments
  name: comments
  nullable: true
  primary_key: 0
  type: TEXT
- input_type: date
  label: spent_on
  name: spent_on
  nullable: false
  primary_key: 0
  type: DATE
- input_type: date
  label: created_at
  name: created_at
  nullable: false
  primary_key: 0
  type: DATETIME
- input_type: date
  label: updated_at
  name: updated_at
  nullable: false
  primary_key: 0
  type: DATETIME
name: time_entries
type: table
