columns:
- input_type: number
  label: TrackId
  name: TrackId
  nullable: false
  primary_key: 1
  type: INTEGER
- input_type: text
  label: Name
  name: Name
  nullable: false
  primary_key: 0
  type: NVARCHAR(200)
- input_type: number
  label: AlbumId
  name: AlbumId
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: number
  label: MediaTypeId
  name: MediaTypeId
  nullable: false
  primary_key: 0
  type: INTEGER
- input_type: number
  label: GenreId
  name: GenreId
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: text
  label: Composer
  name: Composer
  nullable: true
  primary_key: 0
  type: NVARCHAR(220)
- input_type: number
  label: Milliseconds
  name: Milliseconds
  nullable: false
  primary_key: 0
  type: INTEGER
- input_type: number
  label: Bytes
  name: Bytes
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: text
  label: UnitPrice
  name: UnitPrice
  nullable: false
  primary_key: 0
  type: NUMERIC(10, 2)
table_name: Track
