columns:
- input_type: number
  label: UserID
  name: UserID
  nullable: true
  primary_key: 1
  type: INTEGER
- input_type: text
  label: Username
  name: Username
  nullable: false
  primary_key: 0
  type: TEXT
- input_type: text
  label: Password
  name: Password
  nullable: false
  primary_key: 0
  type: TEXT
- input_type: text
  label: Email
  name: Email
  nullable: true
  primary_key: 0
  type: TEXT
- input_type: text
  label: Role
  name: Role
  nullable: true
  primary_key: 0
  type: TEXT
- input_type: date
  label: CreatedAt
  name: CreatedAt
  nullable: true
  primary_key: 0
  type: DATETIME
table_name: Users
