columns:
- autoincrement: true
  input_type: number
  label: id
  name: id
  nullable: true
  primary_key: 1
  type: INTEGER
- input_type: number
  label: issue_id
  name: issue_id
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: text
  label: filename
  name: filename
  nullable: false
  primary_key: 0
  type: VARCHAR(255)
- input_type: text
  label: disk_filename
  name: disk_filename
  nullable: false
  primary_key: 0
  type: VARCHAR(255)
- input_type: number
  label: filesize
  name: filesize
  nullable: false
  primary_key: 0
  type: INTEGER
- input_type: text
  label: content_type
  name: content_type
  nullable: true
  primary_key: 0
  type: VARCHAR(255)
- input_type: number
  label: author_id
  name: author_id
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: date
  label: created_at
  name: created_at
  nullable: false
  primary_key: 0
  type: DATETIME
name: attachments
type: table
