columns:
- input_type: number
  label: CustomerId
  name: CustomerId
  nullable: false
  primary_key: 1
  type: INTEGER
- input_type: text
  label: FirstName
  name: FirstName
  nullable: false
  primary_key: 0
  type: NVARCHAR(40)
- input_type: text
  label: LastName
  name: LastName
  nullable: false
  primary_key: 0
  type: NVARCHAR(20)
- input_type: text
  label: Company
  name: Company
  nullable: true
  primary_key: 0
  type: NVARCHAR(80)
- input_type: text
  label: Address
  name: Address
  nullable: true
  primary_key: 0
  type: NVARCHAR(70)
- input_type: text
  label: City
  name: City
  nullable: true
  primary_key: 0
  type: NVARCHAR(40)
- input_type: text
  label: State
  name: State
  nullable: true
  primary_key: 0
  type: NVARCHAR(40)
- input_type: text
  label: Country
  name: Country
  nullable: true
  primary_key: 0
  type: NVARCHAR(40)
- input_type: text
  label: PostalCode
  name: PostalCode
  nullable: true
  primary_key: 0
  type: NVARCHAR(10)
- input_type: text
  label: Phone
  name: Phone
  nullable: true
  primary_key: 0
  type: NVARCHAR(24)
- input_type: text
  label: Fax
  name: Fax
  nullable: true
  primary_key: 0
  type: NVARCHAR(24)
- input_type: text
  label: Email
  name: Email
  nullable: false
  primary_key: 0
  type: NVARCHAR(60)
- input_type: number
  label: SupportRepId
  name: SupportRepId
  nullable: true
  primary_key: 0
  type: INTEGER
name: Customer
