columns:
- autoincrement: true
  input_type: number
  label: id
  name: id
  nullable: true
  primary_key: 1
  type: INTEGER
- input_type: number
  label: project_id
  name: project_id
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: number
  label: issue_type_id
  name: issue_type_id
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: number
  label: status_id
  name: status_id
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: number
  label: priority_id
  name: priority_id
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: text
  label: subject
  name: subject
  nullable: false
  primary_key: 0
  type: VARCHAR(255)
- input_type: text
  label: description
  name: description
  nullable: true
  primary_key: 0
  type: TEXT
- input_type: number
  label: assigned_to_id
  name: assigned_to_id
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: number
  label: author_id
  name: author_id
  nullable: true
  primary_key: 0
  type: INTEGER
- input_type: date
  label: created_at
  name: created_at
  nullable: false
  primary_key: 0
  type: DATETIME
- input_type: date
  label: updated_at
  name: updated_at
  nullable: false
  primary_key: 0
  type: DATETIME
- input_type: date
  label: start_date
  name: start_date
  nullable: true
  primary_key: 0
  type: DATE
- input_type: date
  label: due_date
  name: due_date
  nullable: true
  primary_key: 0
  type: DATE
- input_type: number
  label: estimated_hours
  name: estimated_hours
  nullable: true
  primary_key: 0
  type: FLOAT
- input_type: number
  label: parent_id
  name: parent_id
  nullable: true
  primary_key: 0
  type: INTEGER
name: issues
type: table
