title: About
component_definitions:
  main_layout:
    attributes:
      title: About
      url: '/blog/about'
    children:
      content_main:
        - type: alert

components:
  - $ref: main_layout