title: Blog

component_definitions:
  main_layout:
    attributes:
      title: Blog
      url: "/blog"
    children:
      content_main:
        - $ref: content_main

  content_main:
    type: content_main
    children:
      - $ref: form_search
      - type: buttons
        children:
          - type: button
            attributes:
              text: New
              hx-get: /blog/post/form
              hx-target: "#form_container"
      - type: form_container
        attributes:
          id: form_container
      - $ref: blog

  blog:
    id: blog
    type: blog
    attributes:
      id: blog
    children:
      - $ref: posts
      
  posts:
    id: posts
    type: posts
    const:
      params:
        data_name: 'posts'
        search_term: ''
        page_size: 10
        page_number: 1
        post_id: ''
    attributes:
      id: posts
      hx-get: /blog/posts?search_term={search_term}&page_size={page_size}&page_number={page_number}
      hx-swap: innerHTML
      hx-target: '#blog'
      hx-trigger: init, newBlogGet from:body
    config:
      buttons:
        prev:
          attributes:
            hx-get: /blog/posts?search_term={search_term}&page_size={page_size}&page_number={page_number - 1}
            hx-swap: 'innerHTML'
            hx-target: '#blog'
        next:
          attributes:
            hx-get: /blog/posts?search_term={search_term}&page_size={page_size}&page_number={page_number + 1}
            hx-swap: 'innerHTML'
            hx-target: '#blog'
    children:
      - $ref: post

  post:
    base: component_definitions.base_data_card
    config:
      buttons:
        delete:
          attributes:
            hx-delete: /blog/posts?post_id={id}
        edit: 
          attributes:
            hx-post: /blog/posts/form?post_id={id}
            hx-target: '#form_container'
        left:
          attributes:
            hx-get: history_back
            hx-target: '#blog'
        right:
          attributes:
            hx-get: /blog/posts?post_id={id}
            hx-target: '#blog'
    attributes:
      id: post
    children:
      - $ref: form_comment
      - $ref: comments
    items:
      - key: id
      - key: title
      - key: content
      - key: status
      - key: visibility
      - key: category_name
      - key: category_id
      - key: author_id
      - key: author_name
      - key: views_count

  comments:
    id: comments
    type: comments
    attributes:
      id: comments
      hx-get: "/api/blog/post/comments?post_id={{posts.id}}"
      hx-swap: innerHTML
      hx-trigger: newPostComment from:body
    children:
      - $ref: comment

  comment:
    id: comment
    type: comment
    attributes:
      id: comment
    items:
      - key: id
      - key: content

  form_search:
    id: form_search
    type: form_search
    attributes:
      title: Search
      hx-get: "/api/blog/posts?api=posts"
      hx-target: "#blog"

  form_edit:
    id: form_edit
    base: component_definitions.base_form_edit
    cols:
      id: {}
      title: {}
      content: {}
      category_id: {}
      author_id: {}
      featured_image:
        input_type: file
        label: Imgae
      status:
        input_type: select
        label: Status
        required: true
        options:
          - { value: draft, label: draft }
          - { value: published, label: published }
          - { value: archived, label: archived }
      visibility:
        input_type: select
        label: Visibility
        required: true
        options:
          - { value: public, label: Public }
          - { value: private, label: Private }
          - { value: password_protected, label: Password Protected }
    config:
      id: posts
    attributes:
      id: form_edit
      hx-post: "/blog/post"
      hx-target: "#target"

  form_comment:
    base: component_definitions.base_form_edit
    cols:
      post_id:
        value: posts.id
        is_hidden: true
      content:
        value: comments.content
    config:
      id: comments
    attributes:
      hx-post: "/blog/post/comment"
      hx-target: "#target"

components:
  - $ref: main_layout

