title: Blog

component_definitions:
  main_layout:
    attributes:
      title: Blog
      url: "/blog"
    children:
      content_main:
        - $ref: content_main

  content_main:
    type: content_main
    children:
      - $ref: form_search
      - type: buttons
        children:
          - type: button
            attributes:
              text: New
              hx-get: /blog/posts/form
              hx-target: "#form_container"
      - type: form_container
        attributes:
          id: form_container
      - $ref: blog

  blog:
    id: blog
    type: blog
    attributes:
      id: blog
    children:
      - $ref: container_posts
      
  container_posts:
    id: container_posts
    type: container_posts
    const:
      params:
        data_name: 'posts'
        search_term: ''
        page_size: 5
        page_number: 1
        post_id: ''
    attributes:
      id: container_posts
      hx-get: /blog/posts?search_term={search_term}&page_size={page_size}&page_number={page_number}
      hx-swap: innerHTML
    #  hx-target: '#container_posts'
      hx-trigger: | 
                    load, 
                    post_blog_post from:body, 
                    put_blog_posts from:body,
                    delete_blog_posts from:body
    children:
      - $ref: posts

  posts:
    base: component_definitions.base_data_card
    const:
      params:
        data_name: 'posts'
        search_term: ''
        page_size: 5
        page_number: 1
        post_id: ''
    config:
      buttons:
        prev:
          attributes:
            hx-get: /blog/posts?search_term={search_term}&page_size={page_size}&page_number={page_number - 1}
            hx-swap: 'innerHTML'
            hx-target: '#container_posts'
        next:
          attributes:
            hx-get: /blog/posts?search_term={search_term}&page_size={page_size}&page_number={page_number + 1}
            hx-swap: 'innerHTML'
            hx-target: '#container_posts'
        delete:
          attributes:
            hx-delete: /blog/posts?id={id}
            hx-target: '#target'
        edit: 
          attributes:
            hx-get: /blog/posts/form?id={id}
            hx-target: '#form_container'
        left:
          attributes:
            hx-get: history_back
            hx-target: '#container_posts'
        right:
          attributes:
            hx-get: /blog/posts?id={id}
            hx-target: '#container_posts'
    attributes:
      id: post
    children:
      - $ref: form_comment
      - $ref: container_comments
    items:
      - key: id
      - key: title
      - key: content
      - key: views_count
      - key: featured_image

  container_comments:
    id: container_comments
    type: container_comments
    attributes:
      id: container_comments
      hx-get: /blog/post/comments?id={id}
      hx-swap: innerHTML
      hx-target: '#container-comments'
      hx-trigger: | 
                    load, 
                    post_blog_post_comments from:body, 
                    delete_blog_post_comments from:body
    children:
      - $ref: comments

  comments:
    id: comments
    base: component_definitions.base_data_card
    const:
      params:
        data_name: 'comments'
        search_term: ''
        page_size: 5
        page_number: 1
        post_id: ''
    config:
      buttons:
        prev:
          attributes:
            hx-get: /blog/post/comments?post_id={id}&search_term={search_term}&page_size={page_size}&page_number={page_number - 1}
            hx-swap: 'innerHTML'
            hx-target: '#container-comments'
        next:
          attributes:
            hx-get: /blog/post/comments?post_id={id}&search_term={search_term}&page_size={page_size}&page_number={page_number + 1}
            hx-swap: 'innerHTML'
            hx-target: '#container-comments'
        delete:
          attributes:
            hx-delete: /blog/post/comments?id={id}
            hx-target: '#target'
    attributes:
      id: comments
    items:
      - key: id
      - key: content

  form_search:
    id: form_search
    type: form_search
    attributes:
      title: Search
      hx-get: "/blog/posts"
      hx-target: "#blog"
      
  form_post:
    id: form_post
    base: component_definitions.base_form_edit
    cols:
      id: {}
      title: {}
      content: {}
      category_id: {}
      author_id: {}
      featured_image:
        input_type: file
        label: Imgae
      status:
        input_type: select
        label: Status
        required: true
        options:
          - { value: draft, label: draft }
          - { value: published, label: published }
          - { value: archived, label: archived }
      visibility:
        input_type: select
        label: Visibility
        required: true
        options:
          - { value: public, label: Public }
          - { value: private, label: Private }
          - { value: password_protected, label: Password Protected }
    config:
      id: posts
    attributes:
      id: form_post
      hx-post: "/blog/posts"
      hx-target: "#target"
      
  form_put:
    id: form_put
    base: component_definitions.base_form_edit
    cols:
      id: {}
      title: {}
      content: {}
      category_id: {}
      author_id: {}
      featured_image:
        input_type: file
        label: Imgae
      status:
        input_type: select
        label: Status
        required: true
        options:
          - { value: draft, label: draft }
          - { value: published, label: published }
          - { value: archived, label: archived }
      visibility:
        input_type: select
        label: Visibility
        required: true
        options:
          - { value: public, label: Public }
          - { value: private, label: Private }
          - { value: password_protected, label: Password Protected }
    config:
      id: posts
    attributes:
      id: form_put
      hx-put: "/blog/posts"
      hx-target: "#target"

  form_comment:
    base: component_definitions.base_form_edit
    cols:
      post_id:
        value: posts.id
        is_hidden: false
      content:
        value: comments.content
    config:
      id: comments
    attributes:
      hx-post: "/blog/post/comments"
      hx-target: "#target"

components:
  - $ref: main_layout

