title: Blog
component_definitions:
  main_layout:
    id: main_layout
    type: layout
    attributes:
      title: Blog
      url: '/blog'
    children:
      content_main:
        # - type: tabs
        #   children:
        #     - type: tab
        #       attributes:
        #         aria-label: "Home"
        #         checked: "checked"
        #       children: 
        #         - $ref: content_main
        #     - type: tab
        #       attributes:
        #         aria-label: "Settings"
        #       children: 
        #         - $ref: content_settings
        #     - type: tab
        #       attributes:
        #         aria-label: "About"
        #       children:
        #         - $ref: content_about
        - $ref: content_main
      left_sidebar:
        - $ref: button
        - type: link
          attributes:
            href: /blog
          config:
            label: Blog
        - type: link
          attributes:
            href: /blog/settings
          config:
            label: Settings
        - type: link
          attributes:
            href: /blog/about
          config:
            label: About
      right_sidebar:
        - type: alert
          attributes:
            class: alert alert-info
            message: This is an informational message.
      
  content_main:
    id: content_main
    type: content_main
    attributes:
      id: content_main
    children:
      - $ref: form_search
      - type: buttons
        children:
          - type: button
            attributes:
              text: New
              hx-post: /blog/post/form
              hx-target: '#form_container'
      #- $ref: form_create
      - type: form_container
        attributes:
          id: form_container
      # - type: file_upload_form
      #   attributes:
      #     label: File Manager
      #- $ref: file_manager
      - $ref: blogs
      
  content_settings:
    id: content_settings
    type: container
    attributes:
      id: content_settings
    children:
      - type: checkbox
      - type: checkbox
      - type: checkbox
      - type: checkbox
      - type: checkbox

  content_about:
    id: content_about
    type: container
    attributes:
      id: content_about
    children:
      - type: alert

  button:
    id: button
    type: button
    attributes: 
      id: button
      text: ok
      hx_get: /protected
      onclick: modal_message.showModal()
 
  blogs:
    id: blogs
    type: blogs
    attributes:
      id: blogs

  posts:
    id: posts
    type: posts
    children:
      # - $ref: form_search
      - $ref: post
   
  post:
    id: post
    type: post
    attributes:
      id: post
    children:
      - $ref: form_comment
      - $ref: comments
    items:
      - key: id
      - key: title
      - key: content
      - key: status
      - key: visibility
      - key: category_name
      - key: category_id
      - key: author_id
      - key: author_name
      - key: views_count

  comments:
    id: comments
    type: comments
    attributes:
      id: comments
      hx-get: '/api/blog/post/comments?post_id={{posts.id}}'
      hx-swap: innerHTML
      hx-trigger: newPostComment from:body
    children:
      - $ref: comment
      
  comment:
    id: comment
    type: comment
    attributes:
      id: comment
    items:
      - key: id
      - key: content

  form_search:
    id: form_search
    type: form_search
    attributes:
      title: Search
      hx-get: "/api/blog/posts?api=posts"
      hx-target: "#blogs"
   
  form_create:
    id: form_create
    type: form_base_type_1
    cols: 
      title: {}
      content: {}
      category_id: {}
      author_id: {}
      featured_image:  
        input_type: file
        label: Imgae
      status: 
        input_type: select
        label: Status
        required: true
        options:
          - {value: draft, label: draft}
          - {value: published, label: published}
          - {value: archived, label: archived}
      visibility: 
        input_type: select
        label: Visibility
        required: true
        options:
          - {value: public, label: Public}
          - {value: private, label: Private}
          - {value: password_protected, label: Password Protected}

    #   country:
    #     input_type: select
    #     label: Country
    #     required: true
    #     options:
    #       - {value: us, label: United States}
    #       - {value: uk, label: United Kingdom}
    #       - {value: ca, label: Canada}
    config:
      title: Create
      mode: create
      btns:
        cancel:
          attributes:
            onclick: "removeForm();"
    attributes:
      id: form_create
      title: Create
      mode: create
      hx-post: "/blog/post"
      hx-target: "#target"
      
  form_edit:
    id: form_edit
    type: form_base_type_1
    cols: 
      id: {}
      title: {}
      content: {}
      category_id: {}
      author_id: {}
      featured_image:  
        input_type: file
        label: Imgae
      status: 
        input_type: select
        label: Status
        required: true
        options:
          - {value: draft, label: draft}
          - {value: published, label: published}
          - {value: archived, label: archived}
      visibility: 
        input_type: select
        label: Visibility
        required: true
        options:
          - {value: public, label: Public}
          - {value: private, label: Private}
          - {value: password_protected, label: Password Protected}

    config:
      title: Edit
      mode: edit
      btns:
        cancel:
          attributes:
            onclick: "removeForm();"
    attributes:
      id: form_edit
      title: Edit
      mode: edit
      hx-put: "/blog/post"
      hx-target: "#target"

  form_comment:
    id: form_comment
    type: form_base_type_1
    cols:
      post_id: 
        value: posts.id
        is_hidden: true
      content: 
        value: comments.content
    config:
      title: Edit
      mode: edit
      btns:
        cancel:
          attributes:
            onclick: "removeForm();"
    attributes:
      id: form_comment
      title: Edit
      mode: edit
      hx-post: "/blog/post/comment"
      hx-target: "#target"


  file_manager:
    id: file_manager
    type: file_manager
    files: get_files
    attributes:
      label: File Manager
    
  main_data_card:
    id: main_data_card
    type: data-card
    config: get_configs
    data: get_table_data

  button_logout:
    id: button_logout
    type: button
    attributes: 
      id: button_logout
      text: logout
      hx_get: /logout
  
  modal_message:
    id: modal_message
    type: modal_message
    attributes:
      id:
        type: string
        value: modal_message
      title:
        type: string
        value: modal
      content:
        type: string
        value: aaaaa
        
  modal_form:
    id: modal_form
    type: modal_form
    attributes:
      id:
        type: string
        value: modal_form
      title:
        type: string
        value: modal
      content:
        type: string
        value: aaaaa
        
  stats:
    id: stats
    type: stats
    children:
      - type: stat
        attributes:
          label: File Manager
          title: a
          color: red
          value: 1
          desc: asdfg
      - type: stat
        attributes:
          label: File Manager
          title: a
          color: red
          value: 2
          desc: asdfg

components:
  - $ref: main_layout
  - $ref: modal_form
  - $ref: modal_message