title: Blog
component_definitions:
  main_layout:
    attributes:
      title: Blog
      url: '/blog'
    children:
      content_main:
        - $ref: content_main

  content_main:
    type: content_main
    attributes:
      id: content_main
    children:
      - $ref: form_search
      - type: buttons
        children:
          - type: button
            attributes:
              text: New
              hx-post: /blog/post/form
              hx-target: '#form_container'
      - type: form_container
        attributes:
          id: form_container
      - $ref: blogs

  blogs:
    id: blogs
    type: blogs
    attributes:
      id: blogs

  posts:
    type: posts
    children:
      - $ref: post
   
  post:
    type: post
    attributes:
      id: post
    children:
      - $ref: form_comment
      - $ref: comments
    items:
      - key: id
      - key: title
      - key: content
      - key: status
      - key: visibility
      - key: category_name
      - key: category_id
      - key: author_id
      - key: author_name
      - key: views_count

  comments:
    id: comments
    type: comments
    attributes:
      id: comments
      hx-get: '/api/blog/post/comments?post_id={{posts.id}}'
      hx-swap: innerHTML
      hx-trigger: newPostComment from:body
    children:
      - $ref: comment
      
  comment:
    id: comment
    type: comment
    attributes:
      id: comment
    items:
      - key: id
      - key: content

  form_search:
    id: form_search
    type: form_search
    attributes:
      title: Search
      hx-get: "/api/blog/posts?api=posts"
      hx-target: "#blogs"

  # form_comment:
  #   base: component_definitions.base_form_edit
  #   #type: form_base_type_1
  #   cols:
  #     post_id: 
  #       value: posts.id
  #       is_hidden: true
  #     content: 
  #       value: comments.content
  #   #config:
  #   #  title: Edit
  #   #  mode: edit
  #   #  btns:
  #   #    cancel:
  #   #      attributes:
  #   #        onclick: "removeForm();"
  #   attributes:
  #     title: Edit
  #     mode: edit
  #     hx-post: "/blog/post/comment"
  #     hx-target: "#target"

  form_comment:
    id: form_comment
    type: form_base_type_1
    cols:
      post_id: 
        value: posts.id
        is_hidden: true
      content: 
        value: comments.content
    config:
      id: comments
      title: Edit
      mode: edit
      btns:
        cancel:
          attributes:
            onclick: "removeForm();"
    attributes:
      id: form_comment
      title: Edit
      mode: edit
      hx-post: "/blog/post/comment"
      hx-target: "#target"

components:
  - $ref: main_layout
