title: Responsive Dashboard with Drawers
component_definitions:
  main_layout:
    id: main_layout
    type: layout
    attributes:
      title: YY
    children:
      left_sidebar:
        - $ref: button
        - $ref: button_pms
        - $ref: button_cms
        - $ref: table_list
      content_main:
        - $ref: content_main
      right_sidebar:
        - $ref: button_logout
        - type: alert
          attributes:
            type:
              type: string
              value: alert-info
            message:
              type: string
              value: This is an informational message.
        
  main_content1:
    id: main_content
    type: main_content
    children:
      - type: grid1
        children:
          - type: card1
            data:
              title: Total Albums
              content: 0
            attributes:
              hx-trigger: load, every 3600s
              hx-get: /api/total_albums
              hx-target: find p
              hx-swap: innerHTML
          - type: card1
            data:
              title: Total Artists
              content: BBB1
            attributes:
              hx-trigger: load, every 3600s
              hx-get: /api/total_artists
              hx-swap: innerHTML
              hx-target: find p
          - type: card1
            data:
              title: AAA2
              content: BBB2
            attributes:
              hx-trigger: load, every 3600s
              hx-get: /api/stats
              hx-swap: innerHTML
              hx-target: find p
          - type: card1
            data:
              title: AAA3
              content: BBB3
            attributes:
              hx-trigger: load, every 3600s
              hx-get: /api/stats
              hx-swap: innerHTML
              hx-target: find p
          # - type: card1
          #   attributes:
          #     title: AAA1
          #     content: BBB1
          # - type: card1
          #   attributes:
          #     title: AAA2
          #     content: BBB2
          # - type: card1
          #   attributes:
          #     title: AAA3
          #     content: BBB3
      # - $ref: main_data_table
      - $ref: main_data_list

  content_main:
    id: content_main
    type: content_main
    children:
      - type: link
        attributes: 
          href: /blog
        config:
          label: Blog
      - type: link
        attributes: 
          href: /test
        config:
          label: Test
      - $ref: main_data_table
    #   - type: table
    #   - type: hero
    #   - type: carousel
    #   - type: tabs
    #   - $ref: stats
    # #   - $ref: main_data_table
    #   - $ref: button
    #   - type: tooltip
    #     attributes:
    #       tip: tip
    #       text: tt
    #   - type: stat
    #     attributes:
    #       label: File Manager
    #     title: a
    #     color: red
    #     value: 1
    #     desc: asdfg

  todo_list:
    id: todo_list
    type: list
    value: get_todos
    
  table_list:
    id: table_list
    type: list
    value: DatabaseManager.get_tables

  # main_data_table:
  #   id: main_data_table
  #   type: data-table
  #   config: get_configs
  #   data: get_table_data
  main_data_table:
    id: main_data_table
    type: data-table
    config: ConfigManager.get_configs
    data: DatabaseManager.get_table_data
    children:
      header:
        - type: data_search_form
          config: ConfigManager.get_configs
          data: DatabaseManager.get_table_data
      content:      
        - $ref: main_data_table_content
      # footer:
      #   - type: data_pagination
      #     config: ConfigManager.get_configs
      #     data: DatabaseManager.get_table_data
        
  main_data_table_content:
    id: main_data_table_content
    type: data_table_content
    config: ConfigManager.get_configs
    data: DatabaseManager.get_table_data

  main_data_card:
    id: main_data_card
    type: data-card
    config: ConfigManager.get_configs
    data: DatabaseManager.get_table_data
  
  main_data_list:
    id: main_data_list
    type: data-list
    config: ConfigManager.get_configs
    data: DatabaseManager.get_table_data
    children:
      header:
        - type: data_search_form
          config: ConfigManager.get_configs
      content:      
        - $ref: main_data_list_content

  main_data_list_content:
    id: main_data_list_content
    type: data_list_content
    config: ConfigManager.get_configs
    data: DatabaseManager.get_table_data

  button:
    id: button
    type: button
    attributes: 
      id: button
      text: ok
      hx_get: /protected
      onclick: modal_message.showModal()
  
  button_pms:
    id: button_pms
    type: button
    attributes: 
      id: button_pms
      text: PMS
      hx_get: /pms
    
  button_cms:
    id: button_cms
    type: button
    attributes: 
      id: button_cms
      text: CMS
      hx_get: /cms

  button_logout:
    id: button_logout
    type: button
    attributes: 
      id: button_logout
      text: logout
      hx_get: /logout
  
  button1:
    id: button1
    type: button
    attributes: 
      id:
        type: string
        value: button1
      text:
        type: string
        value: ok1
      onclick:
        type: string
        value: modal_message.showModal()
        
  modal_message:
    id: modal_message
    type: modal_message
    attributes:
      id:
        type: string
        value: modal_message
      title:
        type: string
        value: modal
      content:
        type: string
        value: aaaaa
        
  modal_form:
    id: modal_form
    type: modal_form
    attributes:
      id:
        type: string
        value: modal_form
      title:
        type: string
        value: modal
      content:
        type: string
        value: aaaaa
        
  form_create:
    id: form_create
    type: form_base
    config:
      title: Create
      mode: create
    attributes:
      title: Create
      mode: create

  form_edit:
    id: form_edit
    type: form_base
    config:
      title: Edit
      mode: edit
    attributes:
      title: Edit
      mode: edit

  form_delete:
    id: form_delete
    type: form_base
    config:
      title: Delete
      mode: delete
    attributes:
      title: Delete
      mode: delete
  
  file_manager:
    id: file_manager
    type: file_manager
    files: get_files
    attributes:
      label: File Manager
      
  stats:
    id: stats
    type: stats
    children:
      - type: stat
        attributes:
          label: File Manager
          title: a
          color: red
          value: 1
          desc: asdfg
      - type: stat
        attributes:
          label: File Manager
          title: a
          color: red
          value: 2
          desc: asdfg
      

components:
  - $ref: main_layout
  - $ref: modal_form
  - $ref: modal_message
  # - $ref: login
#   - $ref: registration_form
#   - type: file_upload_form
#     attributes:
#       label: Profile Picture
#       button: 
#         label: Upload
  # - type: file_manager
  #   files: get_files
  #   attributes:
  #     label: File Manager
  # - $ref: file_manager
  # - $ref: button