title: Responsive Dashboard with Drawers
component_definitions:
  registration_form:
    id: registration_form
    type: form
    attributes:
      class: mt-4 max-w-md mx-auto
      hx_post: /register
      hx_target: "#registration-result"
      hx_encoding: multipart/form-data
      enctype: application/x-www-form-urlencoded
      fields:
        - name: username
          type: text
          label: Username
          placeholder: Enter your username
          required: true
        - name: email
          type: email
          label: Email
          placeholder: Enter your email
          required: true
        - name: password
          type: password
          label: Password
          placeholder: Enter your password
          required: true
      submit_text: Register
    children:
      - type: input
        attributes:
          name: username
          type: text
          label: Username
          placeholder: Enter your username
          required: true
      - type: input
        attributes:
          name: email
          type: email
          label: Email
          placeholder: Enter your email
          required: true
      - type: input
        attributes:
          name: password
          type: password
          label: Password
          placeholder: Enter your password
          required: true
      - type: button
        attributes:
          class: btn btn-primary w-full mt-4
          id: btn_register
          text: Register
      - type: link
        attributes:
          class: btn btn-primary w-full mt-4
          id: link_login
          text: Lgoin
          href: /login

  registration_page:
    id: registration_page
    type: layout_registration
    attributes:
      title: ZHY                        
    children:
      - $ref: registration_form
      - type: alert
        attributes:
          id: registration-result

components:
  - $ref: registration_page