title: Settings
component_definitions:
  main_layout:
    attributes:
      title: Settings
      url: "/blog/settings"
    children:
      content_main:
        # - $ref: form_tag
        - $ref: container_tags

  container_tags:
    base: component_definitions.base_container
    attributes:
      id: container_tags
      hx-get: /api/blog/tags
      hx-trigger: load, newBlogTag from:body
    children:
      - $ref: tags

  tags:
    type: data_card
    attributes:
      id: tags
    items:
      - key: id
      - key: name
      - key: slug
      - key: description

components:
  - $ref: main_layout
